### PR TITLE
pcm: ioplug: Limit transfer size to buffer boundary

### PR DESCRIPTION
**Pull request by aditpape**
Commit 1714332719fc91507ca24dd3567e50d7094b3001 introduced 2nd transfer()
call to transfer all remaining available frames.
If the prior calculated avail value exceeds the buffer size a too large size value
is passed to the underlaying plugin and results in memory corruption if not blocked by plugin internally.
Avail values > buffer size can happen if e.g. xrun detection is disabled,
as avail is calculated by pure difference between hw and app position.
This patch limits 2nd transfer call to remaining rest of a buffer size.

Signed-off-by: Andreas Pape <apape@de.adit-jv.com>

### CODE REVIEW

**Comment by aditpape** [comment]
updated patch to cover cases with avail being exact multiple of buffer_size.

**Comment by aditpape** [comment]
Dear @perexg, can you give indication on PR acceptance?
THX,
Andreas

**Comment by perexg** [comment]
Looking to the code, it does not make sense to copy the capture data in snd_pcm_ioplug_avail_update(). It should be copied in mmap_begin callback. Or we should do the dual-buffering like in _pcm_plugin.c_ (it means separate the external plugin hw_ptr and appl_ptr).

I created https://github.com/alsa-project/alsa-lib/pull/115 with my version. Could you test?

@tiwai - FYI !

**Comment by aditpape** [comment]
Promising approach...
Give me some time for testing.
THX

**Comment by aditpape** [comment]
Tested your #115 -proposal:
Use case: mmap capture access with a proprietary plugin which makes use of the transfer() callback.
Working well for me, did not face any issue.

**Comment by perexg** [comment]
Thank you for the feedback. Closing and merging https://github.com/alsa-project/alsa-lib/pull/115  .

**Pull request closed without merging**
