### PR TITLE
Adjust appl_ptr for multi plugin on rewind/forward operations

### PR DESCRIPTION
**Pull request by sava-j**
* When doing rewind or forward operations, application pointer needs to
  be properly adjusted, in the same way when doing commit/write
  operations.
* Introduce helper functions for manipulating the application pointer.

### CODE REVIEW

**Comment by perexg** [comment]
Looks good, but could you use `snd_pcm_mmap_appl_forward` and `snd_pcm_mmap_appl_backward` ?

**Comment by sava-j** [comment]
Hi,

Sure - I thought it was a bit nicer to introduce separate functions, but giving that we use mmap's functions extensively in multi, it is a better way. I'll amend the commit. Thank you!

**Comment by sava-j** [comment]
Hello @perexg,

I removed the added helper functions and replaced them with `snd_pcm_mmap_appl_forward` and `snd_pcm_mmap_appl_backward`.

Thanks,
Sava

**Comment by perexg** [comment]
Applied in https://github.com/alsa-project/alsa-lib/commit/1aeea94ce81d2ccead17399a99bd0ecfe53025f0 . Thank you for your contribution.

**Pull request closed without merging**
